"""
Project Name: Firestarter
Copyright (c) 2026 Henrik Olsson

Permission is hereby granted under MIT license.

Phase 140 Plan 03 -- TABLE-05 (D-12)

Requirements: TABLE-05

Defect class this closes: a new chip_database.json field entering through
the generator (tools/build_db.py's `chip_entry` construction, or the
VAR-05/D-10 tools/extra_chips.json supplement it merges in) or through a
subset of chips, invisible to a names-only assertion or one that can be
silenced by regenerating tools/baseline/chip_database.baseline.json.

Coverage:
  1. test_top_level_field_inventory_matches -- live top-level per-key
     occurrence counts equal the frozen golden exactly; on mismatch the
     message names added, removed and count-changed keys separately.
  2. test_programming_field_inventory_matches -- same, for the nested
     `programming` object.
  3. test_electrical_field_inventory_matches -- same, for the nested
     `electrical` object.
  4. test_27c_protocol_chip_counts_match -- programming.algorithm counts
     for the three 27C protocols (7, 8, 11) equal 170/127/32.
  5. test_inventory_is_non_vacuous -- 59 manufacturers, 746 chips (both
     sourced from the golden's own `totals`, never hardcoded a second
     time), chip count > 0, every recorded per-key count >= 1, and the
     loaded database is a non-empty mapping.
  6. test_generator_emits_no_key_outside_the_frozen_inventory -- an ast
     walk of tools/build_db.py's `chip_entry` construction, UNIONED with a
     key scan of tools/extra_chips.json (see "Generator scan scope" below),
     equals the golden's generator_emitted_chip_entry_keys exactly.
  7. test_default_targets_resolve_inside_this_repository -- the default
     database/generator/extra-chips targets recompute from _APP_ROOT alone
     (never consulting the environment), exist, are non-empty, and resolve
     under _APP_ROOT; _GOLDEN resolves under _HERE / "golden".
  8. test_this_module_is_collected_and_never_skipped -- this module's
     filename is absent from conftest.py's collect_ignore (Assumption A6:
     that list is armed, pyusb-only), and this module's own source contains
     no skip-bypass call or skip-marker decorator.

Environment seams: FIRESTARTER_CHIP_DB_JSON and FIRESTARTER_BUILD_DB_SOURCE
override the database and generator targets respectively. Both bind at
import (module-level Path resolution below), so they must be set in a
child process environment, never monkeypatched. They exist ONLY to support
planted-violation runs (see this plan's SUMMARY.md for the four RED / one
GREEN transcripts) -- test 7 ignores both by construction, recomputing the
real defaults independently, so a stray redirect left set in CI turns this
gate RED rather than silently green (T-140-12).

Generator scan scope (read this before touching test 6 or the golden's
generator_emitted_chip_entry_keys): chip_database.json is generated by
tools/build_db.py two different ways. Most fields reach the output through
a variable literally named `chip_entry` (a dict literal, plus a handful of
`chip_entry[...] = ...` subscript assignments) -- that path is what
_generator_chip_entry_keys() ast-walks. But five of the eleven top-level
keys (datasheet, provenance, source, verification_note, verification_status)
never pass through a `chip_entry`-named variable at all: they arrive via the
VAR-05/D-10 post-decode merge, `complete_db.setdefault(mfg, []).extend(
extra_chips)`, which reads tools/extra_chips.json (two hand-curated,
non-upstream chip records) and appends its entries wholesale. Confirmed in
-session: an ast walk scoped to `chip_entry` alone finds exactly 21 names,
5 short of the golden's 26 -- and the missing 5 are precisely the
sparse-subset keys this module's own non-names-only design exists to catch.
_EXTRA_CHIPS_PATH is therefore read too, and deliberately NOT made
environment-overridable (only the two seams named above are): it is a
hand-curated data supplement, not generator logic, and it must keep
reflecting the real tree even while FIRESTARTER_BUILD_DB_SOURCE redirects
_GEN_PATH at a scratch copy of build_db.py alone during a planted run --
otherwise a planted-generator run would raise FileNotFoundError instead of
failing on the planted key, which is exactly the "unreachable leg" trap
this milestone's D-15 house rule warns against.

This module reads nothing under /workspaces/firestarter (the sibling
firmware repository) and imports nothing from firestarter_app/tools/ -- it
reads tools/build_db.py and tools/extra_chips.json as plain text/JSON, the
same way it already reads chip_database.json, never via a Python import.

Self-contained path resolution below -- NOT in conftest.py, mirroring the
firmware repo's own tests/ house rule (no shared path-resolution helper) so
this module's target resolution is independently auditable.
"""

import ast
import json
import os
from collections import Counter
from pathlib import Path
from typing import NamedTuple

_HERE = Path(__file__).resolve().parent
_APP_ROOT = _HERE.parent
_DB_REL = "firestarter/data/chip_database.json"
_GEN_REL = "tools/build_db.py"
_EXTRA_CHIPS_REL = "tools/extra_chips.json"
_GOLDEN = _HERE / "golden" / "chip_database_field_inventory.json"
_DB_PATH = Path(os.environ.get("FIRESTARTER_CHIP_DB_JSON", str(_APP_ROOT / _DB_REL)))
_GEN_PATH = Path(
    os.environ.get("FIRESTARTER_BUILD_DB_SOURCE", str(_APP_ROOT / _GEN_REL))
)
# Deliberately NOT environment-overridable -- see "Generator scan scope"
# above. Always the real tree's supplement file, regardless of
# FIRESTARTER_BUILD_DB_SOURCE.
_EXTRA_CHIPS_PATH = _APP_ROOT / _EXTRA_CHIPS_REL


class _WalkCounts(NamedTuple):
    """Two-level {manufacturer: [chip, ...]} scan result."""

    manufacturers: int
    chips: int
    top: "Counter[str]"
    programming: "Counter[str]"
    electrical: "Counter[str]"
    algorithm: "Counter[int]"


def _walk(db: object) -> _WalkCounts:
    """Two-level traversal over {manufacturer: [chip, ...]}.

    A top-level `for key in db` enumerates MANUFACTURERS, not chips, and
    makes every downstream assertion pass vacuously (T-140-11) -- this
    walk descends into each manufacturer's chip list before counting
    anything. It must raise, never silently return empty counters, if the
    loaded object is not a mapping of manufacturer name to a list of chip
    objects.
    """
    if not isinstance(db, dict):
        raise TypeError(
            "chip_database.json must be a top-level dict of "
            f"{{manufacturer: [chip, ...]}}, got {type(db).__name__}"
        )
    manufacturers = 0
    chips = 0
    top: Counter[str] = Counter()
    programming: Counter[str] = Counter()
    electrical: Counter[str] = Counter()
    algorithm: Counter[int] = Counter()
    for mfr_name, chip_list in db.items():
        if not isinstance(chip_list, list):
            raise TypeError(
                f"manufacturer {mfr_name!r} must map to a list of chip "
                f"objects, got {type(chip_list).__name__} -- a top-level "
                "`for key in db` (T-140-11) must never be tolerated silently"
            )
        manufacturers += 1
        for chip in chip_list:
            if not isinstance(chip, dict):
                raise TypeError(
                    f"chip entry under {mfr_name!r} must be a dict, got "
                    f"{type(chip).__name__}"
                )
            chips += 1
            top.update(chip.keys())
            programming.update(chip["programming"].keys())
            electrical.update(chip["electrical"].keys())
            algorithm[chip["programming"]["algorithm"]] += 1
    return _WalkCounts(manufacturers, chips, top, programming, electrical, algorithm)


def _load_db() -> object:
    return json.loads(_DB_PATH.read_text(encoding="utf-8"))


def _load_golden() -> dict:
    return json.loads(_GOLDEN.read_text(encoding="utf-8"))


def _describe_counter_diff(recorded: dict, live: dict) -> str:
    """Explain a level-inventory mismatch by naming added, removed and
    count-changed keys SEPARATELY, each with its counts, rather than a bare
    "dicts differ"."""
    rec_keys = set(recorded)
    live_keys = set(live)
    added = {k: live[k] for k in sorted(live_keys - rec_keys)}
    removed = {k: recorded[k] for k in sorted(rec_keys - live_keys)}
    changed = {
        k: {"recorded": recorded[k], "live": live[k]}
        for k in sorted(rec_keys & live_keys)
        if recorded[k] != live[k]
    }
    parts = []
    if added:
        parts.append(f"added={added}")
    if removed:
        parts.append(f"removed={removed}")
    if changed:
        parts.append(f"count_changed={changed}")
    return "; ".join(parts) if parts else "(no difference detected)"


def _collect_dict_keys(node: ast.Dict, out: set) -> None:
    """Recurse into a `Dict` AST node, collecting every string-literal key,
    including nested `Dict` values and both branches of an `IfExp` reached
    through a `**` spread (a `Dict` key of `None`) -- the `page_size`
    conditional spread's exact shape."""
    for key_node, value_node in zip(node.keys, node.values):
        if key_node is None:
            if isinstance(value_node, ast.IfExp):
                for branch in (value_node.body, value_node.orelse):
                    if isinstance(branch, ast.Dict):
                        _collect_dict_keys(branch, out)
            elif isinstance(value_node, ast.Dict):
                _collect_dict_keys(value_node, out)
            continue
        if isinstance(key_node, ast.Constant) and isinstance(key_node.value, str):
            out.add(key_node.value)
        if isinstance(value_node, ast.Dict):
            _collect_dict_keys(value_node, out)


def _is_chip_entry_subscript_chain(node: ast.Subscript) -> bool:
    cur: ast.expr = node.value
    while isinstance(cur, ast.Subscript):
        cur = cur.value
    return isinstance(cur, ast.Name) and cur.id == "chip_entry"


def _chip_entry_subscript_constants(node: ast.Subscript) -> "list[str]":
    """Every constant string subscript index along a `chip_entry[...]`
    chain, e.g. `chip_entry["electrical"]["vcc"]` -> ["electrical", "vcc"]."""
    indices = []
    cur: ast.expr = node
    while isinstance(cur, ast.Subscript):
        sl = cur.slice
        if isinstance(sl, ast.Constant) and isinstance(sl.value, str):
            indices.append(sl.value)
        cur = cur.value
    return list(reversed(indices))


def _generator_chip_entry_keys(source_text: str) -> "set[str]":
    """ast-walk `source_text` (tools/build_db.py's own source) and collect
    every string key literal reaching a variable literally named
    `chip_entry` -- both its dict-literal construction (including nested
    dicts and the `page_size` conditional `**` spread) and every
    `chip_entry[...] = ...` subscript assignment (including the nested
    `chip_entry["electrical"]["vcc"]` chain). This is the D-12/T-140-10
    half: chip_database.json is GENERATED, so a new key reaching
    `chip_entry` here becomes a new database field the moment anyone
    regenerates -- reachable without ever executing the generator.

    Does NOT see the VAR-05/D-10 extra_chips.json merge -- see
    `_extra_chips_entry_keys` and the module docstring's "Generator scan
    scope" section.
    """
    tree = ast.parse(source_text)
    keys: set[str] = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id == "chip_entry":
                if isinstance(node.value, ast.Dict):
                    _collect_dict_keys(node.value, keys)
            elif isinstance(target, ast.Subscript) and _is_chip_entry_subscript_chain(
                target
            ):
                keys.update(_chip_entry_subscript_constants(target))
    return keys


def _extra_chips_entry_keys(extra_chips_path: Path) -> "set[str]":
    """The generator also emits chip-entry fields it never constructs via a
    `chip_entry`-named variable at all: tools/extra_chips.json (VAR-05/D-10)
    is merged wholesale into the output by
    `complete_db.setdefault(mfg, []).extend(extra_chips)` -- a plain list
    extend, not a `chip_entry`-named assignment, so
    `_generator_chip_entry_keys` is structurally blind to it. Read as data
    (json.loads), never imported, exactly like this module's existing
    treatment of chip_database.json itself."""
    if not extra_chips_path.exists():
        return set()
    extra_db = json.loads(extra_chips_path.read_text(encoding="utf-8"))
    keys: set[str] = set()
    for _mfr, chip_list in extra_db.items():
        if not isinstance(chip_list, list):
            continue
        for chip in chip_list:
            if not isinstance(chip, dict):
                continue
            keys.update(chip.keys())
            keys.update(chip.get("programming", {}).keys())
            keys.update(chip.get("electrical", {}).keys())
    return keys


def test_top_level_field_inventory_matches() -> None:
    """TABLE-05: chip_database.json's top-level field inventory (names AND
    per-key occurrence counts) is frozen. A count change means a field was
    added to, or removed from, some subset of chips -- exactly the class of
    schema drift a names-only assertion cannot see."""
    golden = _load_golden()
    live = _walk(_load_db()).top
    recorded = golden["levels"]["top"]
    assert dict(live) == recorded, (
        "chip_database.json top-level field inventory diverged from the "
        f"frozen golden -- {_describe_counter_diff(recorded, dict(live))}"
    )


def test_programming_field_inventory_matches() -> None:
    golden = _load_golden()
    live = _walk(_load_db()).programming
    recorded = golden["levels"]["programming"]
    assert dict(live) == recorded, (
        "chip_database.json programming-level field inventory diverged "
        f"from the frozen golden -- "
        f"{_describe_counter_diff(recorded, dict(live))}"
    )


def test_electrical_field_inventory_matches() -> None:
    golden = _load_golden()
    live = _walk(_load_db()).electrical
    recorded = golden["levels"]["electrical"]
    assert dict(live) == recorded, (
        "chip_database.json electrical-level field inventory diverged from "
        f"the frozen golden -- {_describe_counter_diff(recorded, dict(live))}"
    )


def test_27c_protocol_chip_counts_match() -> None:
    """TABLE-05 / F-140-04: programming.algorithm chip counts for the three
    27C protocols are frozen. A count change invalidates every per-protocol
    figure this milestone cites -- F-140-04's pulse distribution and the
    D-09 citation scope clauses both assume these counts."""
    golden = _load_golden()
    live_algorithm = _walk(_load_db()).algorithm
    recorded = {int(k): v for k, v in golden["protocol_chip_counts"].items()}
    live = {proto: live_algorithm[proto] for proto in recorded}
    assert live == recorded, (
        "27C protocol chip counts (programming.algorithm in {7, 8, 11}) "
        f"diverged from the frozen golden -- recorded={recorded} live={live}. "
        "A count change invalidates every per-protocol figure this "
        "milestone cites, including F-140-04's pulse distribution and the "
        "D-09 citation scope clauses."
    )


def test_inventory_is_non_vacuous() -> None:
    """Non-vacuity floor (D-15 / T-140-11): the scan must have actually
    walked something. Every message reports the scanned counts so a
    zero-scan (a vacuous top-level `for key in db`, or a `{}` target) can
    never read as a pass."""
    golden = _load_golden()
    db = _load_db()
    assert isinstance(db, dict) and len(db) > 0, (
        f"non-vacuous guard: chip_database.json must load as a non-empty "
        f"dict, got {type(db).__name__!r}"
    )
    counts = _walk(db)
    expected_manufacturers = golden["totals"]["manufacturers"]
    expected_chips = golden["totals"]["chips"]
    assert counts.manufacturers == expected_manufacturers, (
        f"non-vacuous guard: expected {expected_manufacturers} "
        f"manufacturers (frozen), scanned {counts.manufacturers}"
    )
    assert counts.chips == expected_chips and counts.chips > 0, (
        f"non-vacuous guard: expected {expected_chips} chips (frozen) and "
        f"> 0, scanned {counts.chips}"
    )
    for level_name, counter in (
        ("top", counts.top),
        ("programming", counts.programming),
        ("electrical", counts.electrical),
    ):
        for key, count in counter.items():
            assert count >= 1, (
                f"non-vacuous guard: {level_name}.{key} recorded a scanned "
                f"count of {count}, expected >= 1"
            )


def test_generator_emits_no_key_outside_the_frozen_inventory() -> None:
    """TABLE-05 / T-140-10: chip_database.json is GENERATED
    (infoic.xml + extra_chips.json -> tools/build_db.py), never
    hand-edited, so a new key reaching the generator's output becomes a new
    database field the moment anyone runs `python tools/build_db.py` --
    this must be caught by reading the generator's source and its data
    supplement, not only the database they already produced."""
    golden = _load_golden()
    live = _generator_chip_entry_keys(_GEN_PATH.read_text(encoding="utf-8"))
    live |= _extra_chips_entry_keys(_EXTRA_CHIPS_PATH)
    recorded = set(golden["generator_emitted_chip_entry_keys"])
    assert live == recorded, (
        "the generator's emitted chip-entry key set diverged from the "
        f"frozen golden -- added={sorted(live - recorded)} "
        f"removed={sorted(recorded - live)}. chip_database.json is "
        "generated, so a new key here becomes a new database field the "
        "moment anyone regenerates it."
    )


def test_default_targets_resolve_inside_this_repository() -> None:
    """T-140-12: recompute the default database/generator/extra-chips
    targets from _APP_ROOT directly, WITHOUT consulting
    FIRESTARTER_CHIP_DB_JSON or FIRESTARTER_BUILD_DB_SOURCE -- a stray
    redirect left set in CI must turn this gate RED by pointing _DB_PATH /
    _GEN_PATH elsewhere while this test still asserts the untouched
    defaults exist, never silently green."""
    default_db = _APP_ROOT / _DB_REL
    default_gen = _APP_ROOT / _GEN_REL
    default_extra = _APP_ROOT / _EXTRA_CHIPS_REL
    app_root_resolved = _APP_ROOT.resolve()
    for path, label in (
        (default_db, "database"),
        (default_gen, "generator"),
        (default_extra, "extra-chips supplement"),
    ):
        assert path.exists(), f"default {label} target missing: {path}"
        assert path.stat().st_size > 0, f"default {label} target is empty: {path}"
        assert path.resolve().is_relative_to(app_root_resolved), (
            f"default {label} target {path} resolved outside _APP_ROOT {_APP_ROOT}"
        )
    assert _GOLDEN.resolve().is_relative_to((_HERE / "golden").resolve()), (
        f"_GOLDEN {_GOLDEN} did not resolve under {_HERE / 'golden'}"
    )


def test_this_module_is_collected_and_never_skipped() -> None:
    """Assumption A6: tests/conftest.py's collect_ignore is armed (pyusb
    only) -- disprove it for THIS module specifically, and self-scan for
    skip bypasses. Both are the same D-15 "a pre-authored gate leg can be
    unreachable" concern."""
    conftest_source = (_HERE / "conftest.py").read_text(encoding="utf-8")
    this_name = Path(__file__).name
    assert this_name not in conftest_source, (
        f"{this_name} appears in conftest.py -- collect_ignore is armed "
        "(pyusb only, Assumption A6) and must never grow to cover this "
        "module"
    )
    this_source = Path(__file__).read_text(encoding="utf-8")
    for line in this_source.splitlines():
        stripped = line.strip()
        assert not stripped.startswith("pytest.skip"), (
            f"found a skip-bypass call at: {line!r} -- this gate must FAIL, "
            "never silently skip"
        )
        assert not stripped.startswith("@pytest.mark.skipif"), (
            f"found a skip-marker decorator at: {line!r} -- this gate must "
            "FAIL, never silently skip"
        )
