"""
Drift gate test for the SDP bus_config codegen (TRACE-02 / D-10 / D-11 /
T-116-02-EDIT / T-116-02-HOLLOW).

Asserts that re-running gen_sdp_bus_config.py produces a byte-identical copy
of the committed sdp_bus_config.h. Fails if pinouts.json is edited (or the
committed header hand-edited) without regenerating the header.

Mirrors the existing validation_matrix.h drift gate pattern
(tests/test_gen_validation_header.py).
"""

import json
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).parent.parent.parent
_APP_DIR = _REPO_ROOT / "firestarter_app"
_GEN_SCRIPT = _APP_DIR / "tools" / "gen_sdp_bus_config.py"
_REAL_PINOUTS = _APP_DIR / "firestarter" / "data" / "pinouts.json"
_COMMITTED_HEADER = (
    _REPO_ROOT
    / "firestarter"
    / "test"
    / "native"
    / "avr"
    / "_shared"
    / "sdp_bus_config.h"
)

# The firmware sub-repo may be absent in standalone CI (firestarter_app checked
# out alone). The committed sdp_bus_config.h lives in the firestarter repo, so
# the cross-repo tests below skip cleanly when that checkout is absent -- they
# run from the meta work-tree where both repos sit side by side. Mirrors the
# FW_ABSENT skip pattern in test_revision_constants_parity.py /
# test_gen_validation_header.py (D-11 -- scoped to this file only; TRACE-05's
# DB invariant test must never carry this skipif).
_FW_HEADER_ABSENT = not _COMMITTED_HEADER.exists()
_requires_fw_header = pytest.mark.skipif(
    _FW_HEADER_ABSENT,
    reason="firestarter firmware checkout absent (sdp_bus_config.h)",
)


@_requires_fw_header
def test_committed_header_exists() -> None:
    """The committed header must exist in the firestarter submodule."""
    assert _COMMITTED_HEADER.exists(), (
        f"sdp_bus_config.h not found: {_COMMITTED_HEADER}\n"
        "Run: cd firestarter_app && python tools/gen_sdp_bus_config.py"
    )


@_requires_fw_header
def test_committed_header_has_do_not_edit_banner() -> None:
    """Header must start with the DO NOT EDIT banner."""
    content = _COMMITTED_HEADER.read_text(encoding="utf-8")
    assert content.startswith(
        "/* DO NOT EDIT -- generated by tools/gen_sdp_bus_config.py"
    ), "Header is missing the DO NOT EDIT banner"


@_requires_fw_header
def test_codegen_produces_byte_identical_output() -> None:
    """Re-running the codegen must produce a byte-identical header (drift gate).

    This test fails when:
    - pinouts.json is edited but gen_sdp_bus_config.py is not re-run.
    - gen_sdp_bus_config.py emitter logic changes but the committed header is stale.
    - the committed header was hand-edited (T-116-02-EDIT).
    """
    with tempfile.NamedTemporaryFile(suffix=".h", delete=False) as tmp:
        tmp_path = Path(tmp.name)

    try:
        result = subprocess.run(
            [
                sys.executable,
                str(_GEN_SCRIPT),
                "--target",
                str(tmp_path),
            ],
            capture_output=True,
            text=True,
            cwd=str(_APP_DIR),
        )
        assert result.returncode == 0, (
            f"gen_sdp_bus_config.py failed (exit {result.returncode}):\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )

        regenerated = tmp_path.read_bytes()
        committed = _COMMITTED_HEADER.read_bytes()

        assert regenerated == committed, (
            "sdp_bus_config.h is STALE -- re-run to update:\n"
            "  cd firestarter_app && python tools/gen_sdp_bus_config.py\n"
            f"\nRegenerated output ({len(regenerated)} bytes) differs from "
            f"committed header ({len(committed)} bytes).\n"
            "Diff hint: the first differing byte position indicates the change."
        )
    finally:
        tmp_path.unlink(missing_ok=True)


def test_bad_pinout_fails_closed_and_writes_nothing() -> None:
    """Non-vacuity leg (T-116-02-HOLLOW): prove the gate CAN fail.

    Plants a deliberately-broken pinouts.json (one of the four 0x0D pinouts'
    rw-pin changed to a value that resolves to a different bus line than the
    independently-measured reference), points the generator's --pinouts
    override seam at it, and asserts:
      - the generator exits non-zero (1 -- validation failure)
      - nothing is written to --target

    This is NOT a real chip-database checkout requirement -- it runs
    unconditionally (no FW_ABSENT skip) since it never touches the committed
    header, only the generator's own validate-before-emit contract.
    """
    assert _REAL_PINOUTS.exists(), f"real pinouts.json missing: {_REAL_PINOUTS}"
    real_pinouts = json.loads(_REAL_PINOUTS.read_text(encoding="utf-8"))

    # DIP28_28C256's rw-pin is [27] (-> RURP bus line 14, AT28C256's reference
    # rw_line). Flip it to [21] (-> a different, already-used bus line) so the
    # derived rw_line for AT28C256 diverges from the pinned reference value 14.
    assert real_pinouts["DIP28_28C256"]["pins"]["rw-pin"] == [27], (
        "test fixture assumption stale -- DIP28_28C256 rw-pin is no longer [27]; "
        "update this planted-fault value"
    )
    broken_pinouts = json.loads(json.dumps(real_pinouts))  # deep copy
    broken_pinouts["DIP28_28C256"]["pins"]["rw-pin"] = [21]

    with tempfile.NamedTemporaryFile(
        suffix=".json", delete=False, mode="w", encoding="utf-8"
    ) as bad_pinouts_file:
        json.dump(broken_pinouts, bad_pinouts_file)
        bad_pinouts_path = Path(bad_pinouts_file.name)

    with tempfile.NamedTemporaryFile(suffix=".h", delete=False) as tmp:
        tmp_out = Path(tmp.name)
        # Remove the file so we can detect if codegen writes to it.
        tmp_out.unlink()

    try:
        result = subprocess.run(
            [
                sys.executable,
                str(_GEN_SCRIPT),
                "--pinouts",
                str(bad_pinouts_path),
                "--target",
                str(tmp_out),
            ],
            capture_output=True,
            text=True,
            cwd=str(_APP_DIR),
        )
        assert result.returncode == 1, (
            f"Expected exit code 1 for a planted-bad pinouts.json, got "
            f"{result.returncode}\nstdout: {result.stdout}\nstderr: {result.stderr}"
        )
        assert not tmp_out.exists(), (
            "Script wrote output even though derivation was invalid "
            "(must validate before emission)"
        )
    finally:
        bad_pinouts_path.unlink(missing_ok=True)
        tmp_out.unlink(missing_ok=True)
