"""
Drift gate test for the validation matrix codegen (HARN-02 / D-01 / T-71-DRIFT).

Asserts that re-running gen_validation_header.py produces a byte-identical copy
of the committed validation_matrix.h. Fails if the spec is edited without
regenerating the header.

Mirrors the existing messages.h drift gate pattern.
"""

import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).parent.parent.parent
_APP_DIR = _REPO_ROOT / "firestarter_app"
_GEN_SCRIPT = _APP_DIR / "tools" / "gen_validation_header.py"
_SPEC = _APP_DIR / "tools" / "validation_matrix_spec.json"
_COMMITTED_HEADER = (
    _REPO_ROOT
    / "firestarter"
    / "test"
    / "native"
    / "avr"
    / "_shared"
    / "validation_matrix.h"
)

# The firmware sub-repo may be absent in standalone CI (firestarter_app checked
# out alone). The committed validation_matrix.h lives in the firestarter repo, so
# the cross-repo tests below skip cleanly when that checkout is absent — they run
# from the meta work-tree where both repos sit side by side. Mirrors the
# FW_ABSENT skip pattern in test_revision_constants_parity.py.
_FW_HEADER_ABSENT = not _COMMITTED_HEADER.exists()
_requires_fw_header = pytest.mark.skipif(
    _FW_HEADER_ABSENT,
    reason="firestarter firmware checkout absent (validation_matrix.h)",
)


@_requires_fw_header
def test_committed_header_exists() -> None:
    """The committed header must exist in the firestarter submodule."""
    assert _COMMITTED_HEADER.exists(), (
        f"validation_matrix.h not found: {_COMMITTED_HEADER}\n"
        "Run: cd firestarter_app && python tools/gen_validation_header.py"
    )


@_requires_fw_header
def test_committed_header_has_do_not_edit_banner() -> None:
    """Header must start with the DO NOT EDIT banner."""
    content = _COMMITTED_HEADER.read_text(encoding="utf-8")
    assert content.startswith(
        "/* DO NOT EDIT -- generated by tools/gen_validation_header.py"
    ), "Header is missing the DO NOT EDIT banner"


@_requires_fw_header
def test_committed_header_has_val_families() -> None:
    """Header must contain VAL_FAMILIES and VAL_FAMILY_COUNT."""
    content = _COMMITTED_HEADER.read_text(encoding="utf-8")
    assert "VAL_FAMILIES" in content, "Header is missing VAL_FAMILIES"
    assert "VAL_FAMILY_COUNT" in content, "Header is missing VAL_FAMILY_COUNT"


@_requires_fw_header
def test_committed_header_has_11_rows() -> None:
    """Header must contain exactly 11 rows (one per host-dispatchable protocol across 6 families).

    5v_page contributes only protocol 0x05: 0x35 and 0x39 are firmware-dispatch-only
    (zero DB chips) and are intentionally omitted from the host matrix (CR-02 resolution).
    The native suite test_val_5v_page.cpp still covers 0x35/0x39 directly.
    """
    content = _COMMITTED_HEADER.read_text(encoding="utf-8")
    # Count lines that start with "    { 0x" (each row in the VAL_FAMILIES table)
    row_lines = [
        line for line in content.splitlines() if line.strip().startswith("{ 0x")
    ]
    assert len(row_lines) == 11, (
        f"Expected 11 VAL_FAMILIES rows (removed one protocol x 2 rows for 0x35/0x39: 13->11), "
        f"got {len(row_lines)}: {row_lines}"
    )


@_requires_fw_header
def test_codegen_produces_byte_identical_output() -> None:
    """Re-running the codegen must produce a byte-identical header (drift gate).

    This test fails when:
    - validation_matrix_spec.json is edited but gen_validation_header.py is not re-run.
    - gen_validation_header.py emitter logic changes but the committed header is stale.
    """
    with tempfile.NamedTemporaryFile(suffix=".h", delete=False) as tmp:
        tmp_path = Path(tmp.name)

    try:
        result = subprocess.run(
            [
                sys.executable,
                str(_GEN_SCRIPT),
                "--spec",
                str(_SPEC),
                "--target",
                str(tmp_path),
            ],
            capture_output=True,
            text=True,
            cwd=str(_APP_DIR),
        )
        assert result.returncode == 0, (
            f"gen_validation_header.py failed (exit {result.returncode}):\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )

        regenerated = tmp_path.read_bytes()
        committed = _COMMITTED_HEADER.read_bytes()

        assert regenerated == committed, (
            "validation_matrix.h is STALE — re-run to update:\n"
            "  cd firestarter_app && python tools/gen_validation_header.py\n"
            f"\nRegenerated output ({len(regenerated)} bytes) differs from "
            f"committed header ({len(committed)} bytes).\n"
            "Diff hint: the first differing byte position indicates the change."
        )
    finally:
        tmp_path.unlink(missing_ok=True)


def test_validate_spec_called_before_emission() -> None:
    """Script must validate the spec before writing output.

    With a malformed spec, the script must exit 1 (schema error)
    and NOT write any output file.
    """
    import json

    with tempfile.NamedTemporaryFile(
        suffix=".json", delete=False, mode="w", encoding="utf-8"
    ) as bad_spec_file:
        json.dump({"schema_version": "NOT_AN_INT", "families": []}, bad_spec_file)
        bad_spec_path = Path(bad_spec_file.name)

    with tempfile.NamedTemporaryFile(suffix=".h", delete=False) as tmp:
        tmp_out = Path(tmp.name)
        # Remove the file so we can detect if codegen writes to it
        tmp_out.unlink()

    try:
        result = subprocess.run(
            [
                sys.executable,
                str(_GEN_SCRIPT),
                "--spec",
                str(bad_spec_path),
                "--target",
                str(tmp_out),
            ],
            capture_output=True,
            text=True,
            cwd=str(_APP_DIR),
        )
        assert result.returncode == 1, (
            f"Expected exit code 1 for invalid spec, got {result.returncode}"
        )
        assert not tmp_out.exists(), (
            "Script wrote output even though spec was invalid (must validate before emission)"
        )
    finally:
        bad_spec_path.unlink(missing_ok=True)
        tmp_out.unlink(missing_ok=True)


@_requires_fw_header
@pytest.mark.parametrize(
    "handler",
    [
        "configure_eprom",
        "configure_eeprom28c",
        "configure_flash_nor_unlock",
        "configure_flash_5v_page",
        "configure_flash_intel",
        "configure_sram",
    ],
)
def test_all_6_handlers_present_in_committed_header(handler: str) -> None:
    """Each of the 6 configure_* handler names must appear in the committed header."""
    content = _COMMITTED_HEADER.read_text(encoding="utf-8")
    assert handler in content, (
        f'Handler "{handler}" not found in committed validation_matrix.h'
    )
