#!/usr/bin/env python3
"""
Firestarter v1.22 SDP bus_config ground truth codegen (TRACE-02 / D-08 / D-09 / D-11).

Derives, validates and emits the `bus_config_t` ground truth the Phase-116 trace
suites assert against, for five representative AT28C-family chips spanning the
four `0x0D` (EEPROM_PARALLEL) pinouts:

  firestarter/test/native/avr/_shared/sdp_bus_config.h

Unlike `gen_validation_header.py` (whose "spec" is an authored JSON file), this
generator's derivation is the HOST'S OWN LIVE CODE PATH — it imports
`EpromDatabase` from `firestarter.database` and calls `get_eprom()` /
`convert_to_programmer()` for each chip, then translates the resulting
programmer dict into `bus_config_t` fields exactly the way
`firestarter/src/json_parser.c`'s `parse_bus_config` does. It never
reimplements `convert_to_programmer` — a reimplementation is a second thing
that can be wrong, and the whole point of this generator is that the trace
ground truth is NOT a transcription (D-08).

Mirrors the established `tools/gen_validation_header.py` shape:
  - Validate-first: validate_rows() raises ValueError on any derivation
    violation BEFORE emission (T-116-02-STALE mitigation).
  - Deterministic: fixed chip order, no timestamps, LF endings.
  - Banner: DO NOT EDIT with re-run instructions.
  - Path.write_text(encoding="utf-8", newline="\\n") for byte-identical output.

Exit codes:
  0 -- derivation valid, header emitted successfully (or --check found no drift)
  1 -- derived rows failed validation (a value diverged from the independently
       measured reference -- pinouts.json moved and the trace goldens are stale)
  2 -- a required chip or its pinout was not found in the chip database

TRACE-02 / D-08 / D-09 / D-11 analog of HARN-02 / D-01.
"""

import argparse
import sys
from pathlib import Path

# ===========================================================================
# 1. DEFAULTS (relative to this script's location)
# ===========================================================================

_TOOLS_DIR = Path(__file__).parent
_APP_ROOT = _TOOLS_DIR.parent
_TARGET_DEFAULT = (
    _APP_ROOT.parent
    / "firestarter"
    / "test"
    / "native"
    / "avr"
    / "_shared"
    / "sdp_bus_config.h"
)
_PINOUTS_DEFAULT = _APP_ROOT / "firestarter" / "data" / "pinouts.json"

# Make the `firestarter` package importable when this script is run directly
# (mirrors the sibling-repo path derivation convention in gen_validation_header.py).
sys.path.insert(0, str(_APP_ROOT))

# ===========================================================================
# 2. REPRESENTATIVE CHIP SET (D-09)
# ===========================================================================

# One chip per 0x0D pinout, plus a second DIP32_28C512_EEPROM size band.
# That pinout alone spans 64 KB to 512 KB; AT28C010 and AT28C040 share an
# IDENTICAL bus_config, so the band is distinguished by mem_size and prior
# register state, not by bus_config (RESEARCH SUMMARY.md, "Note" under F5's
# per-pinout table). Fixed order -- this IS the emission order.
REPRESENTATIVE_CHIPS = [
    "AT28C256",  # DIP28_28C256, 32768 B
    "AT28C64",  # DIP28_28C64, 8192 B
    "AT28C16",  # DIP24_2816, 2048 B
    "AT28C010",  # DIP32_28C512_EEPROM, 131072 B
    "AT28C040",  # DIP32_28C512_EEPROM, 524288 B -- same bus_config as AT28C010
]

# Independently-measured reference values (RESEARCH.md SUMMARY.md §F5 /
# §Code Examples), in the fixed REPRESENTATIVE_CHIPS order above. A derived
# value disagreeing with these means pinouts.json moved and the trace goldens
# are stale -- fail loudly rather than emit fresh ground truth silently.
_EXPECTED_MATCHING_LINES = [14, 13, 11, 16, 16]
_EXPECTED_RW_LINE = [14, 14, 11, 20, 20]
_EXPECTED_ADDRESS_MASK = [0xBFFF, 0x1FFF, 0x07FF, 0xFFFF, 0xFFFF]

ADDRESS_LINES_SIZE = 20  # firestarter/include/firestarter.h:73

BANNER = (
    "/* DO NOT EDIT -- generated by tools/gen_sdp_bus_config.py\n"
    " * Re-run after editing firestarter_app/firestarter/data/pinouts.json */\n"
    "\n"
)


# ===========================================================================
# 3. DERIVATION (D-08) -- mirrors src/json_parser.c's parse_bus_config exactly
# ===========================================================================


class DerivationError(Exception):
    """A required chip or pinout could not be resolved (exit code 2)."""


def derive_row(db, chip_name: str) -> dict:
    """Derive one bus_config_t row for `chip_name` via the host's own
    EpromDatabase.get_eprom() + convert_to_programmer() path -- never a
    reimplementation of that translation.

    Field derivation mirrors src/json_parser.c:214-243 (parse_bus_config)
    field-for-field:
      address_lines[j] = bus[j]
      address_mask |= 1 << bus[j]
      matching_lines = first index j where bus[j] != j, else len(bus)
      address_lines[len(bus)] = 0xFF (sentinel) when len(bus) < ADDRESS_LINES_SIZE
      rw_line from the pinout's rw-pin
      vpp_line = 0xFF (no 0x0D pinout declares vpp-pin)
      static_high_mask = 0 (no 0x0D pinout declares static-high-pins)
    """
    full = db.get_eprom(chip_name)
    if not full:
        raise DerivationError(f"chip not found in database: {chip_name!r}")

    programmer = db.convert_to_programmer(full)
    bus_config = programmer.get("bus-config") or {}
    bus = bus_config.get("bus")
    if not bus:
        raise DerivationError(
            f"chip {chip_name!r} yielded an empty/missing 'bus' list "
            f"from convert_to_programmer()"
        )

    rw_pin = bus_config.get("rw-pin")
    vpp_pin = bus_config.get("vpp-pin")
    static_high = bus_config.get("static-high")

    address_mask = 0
    matching_lines = None
    for j, line in enumerate(bus):
        address_mask |= 1 << line
        if matching_lines is None and line != j:
            matching_lines = j
    if matching_lines is None:
        matching_lines = len(bus)

    address_lines = list(bus)
    if len(bus) < ADDRESS_LINES_SIZE:
        address_lines.append(0xFF)  # sentinel, mirrors json_parser.c:230

    return {
        "chip_name": chip_name,
        "pinout_name": full.get("pin-map"),
        "mem_size": full.get("memory-size", 0),
        "bus": bus,
        "address_lines": address_lines,
        "address_mask": address_mask,
        "matching_lines": matching_lines,
        "rw_line": rw_pin,
        "vpp_pin": vpp_pin,
        "static_high": static_high,
    }


def derive_rows(pinouts_path: Path) -> list:
    """Derive all REPRESENTATIVE_CHIPS rows via the real EpromDatabase.

    `pinouts_path` is a fail-closed input-override seam (added in this plan
    to let the paired drift-gate pytest plant a deliberately-broken pinouts
    file without editing the real, clean pinouts.json). It must exist -- a
    missing override path is an error, never a silent fall-back to the real
    file.

    `EpromDatabase.__init__` has no constructor seam for an alternate
    pinouts.json path, so this loads the JSON at `pinouts_path` directly and
    assigns it onto `db.pin_maps` (the exact attribute `_initialize_database_core`
    populates from the real file via `_read_config_file("pinouts.json")`)
    BEFORE calling `get_eprom()`/`convert_to_programmer()` -- every subsequent
    derivation call still goes through the real, unmodified
    `get_bus_config()`/`convert_to_programmer()` code path; only the input
    data is swapped.
    """
    if not pinouts_path.is_file():
        raise DerivationError(f"pinouts file not found: {pinouts_path}")

    import json

    from firestarter.database import EpromDatabase

    db = EpromDatabase(skip_local_override=True)
    db.pin_maps = json.loads(pinouts_path.read_text(encoding="utf-8"))

    rows = []
    for chip_name in REPRESENTATIVE_CHIPS:
        rows.append(derive_row(db, chip_name))
    return rows


# ===========================================================================
# 4. VALIDATION (T-116-02-STALE mitigation) -- load-bearing ordering: this
#    MUST run and raise BEFORE any emission.
# ===========================================================================


def validate_rows(rows: list) -> None:
    """Raise ValueError on any derivation violation. Emits nothing on failure.

    Validates:
    - every chip resolved and yielded a non-empty bus list, every bus line < 20
    - rw-pin present for all five; no vpp-pin and no static-high-pins on any
      of the four pinouts (SDP-F8's observable -- recorded, not acted on)
    - derived matching_lines / rw_line / address_mask equal the independently
      measured reference values, in the fixed REPRESENTATIVE_CHIPS order
    - the two DIP32 rows (AT28C010, AT28C040) have byte-identical bus_config
      (the D-09 premise)
    """
    if len(rows) != len(REPRESENTATIVE_CHIPS):
        raise ValueError(
            f"expected {len(REPRESENTATIVE_CHIPS)} derived rows, got {len(rows)}"
        )

    for row in rows:
        name = row["chip_name"]
        if not row["bus"]:
            raise ValueError(f"{name}: empty bus list")
        for line in row["bus"]:
            if line >= ADDRESS_LINES_SIZE:
                raise ValueError(
                    f"{name}: bus line {line} >= ADDRESS_LINES_SIZE ({ADDRESS_LINES_SIZE})"
                )
        if row["rw_line"] is None:
            raise ValueError(
                f"{name}: rw-pin missing from convert_to_programmer output"
            )
        if row["vpp_pin"] is not None:
            raise ValueError(
                f"{name}: unexpected vpp-pin {row['vpp_pin']!r} on a 0x0D pinout "
                f"(all four 0x0D pinouts are 5V-only, SDP-F8)"
            )
        if row["static_high"]:
            raise ValueError(
                f"{name}: unexpected static-high-pins {row['static_high']!r} "
                f"on a 0x0D pinout"
            )

    for i, row in enumerate(rows):
        name = row["chip_name"]
        expected_ml = _EXPECTED_MATCHING_LINES[i]
        expected_rw = _EXPECTED_RW_LINE[i]
        expected_mask = _EXPECTED_ADDRESS_MASK[i]
        if row["matching_lines"] != expected_ml:
            raise ValueError(
                f"{name}: derived matching_lines {row['matching_lines']} != "
                f"expected {expected_ml} (pinouts.json may have moved -- "
                f"trace goldens would be stale)"
            )
        if row["rw_line"] != expected_rw:
            raise ValueError(
                f"{name}: derived rw_line {row['rw_line']} != expected {expected_rw} "
                f"(pinouts.json may have moved -- trace goldens would be stale)"
            )
        if row["address_mask"] != expected_mask:
            raise ValueError(
                f"{name}: derived address_mask 0x{row['address_mask']:X} != "
                f"expected 0x{expected_mask:X} (pinouts.json may have moved -- "
                f"trace goldens would be stale)"
            )

    # Premise: the two DIP32 rows share an identical bus_config.
    dip32_rows = [r for r in rows if r["chip_name"] in ("AT28C010", "AT28C040")]
    if len(dip32_rows) == 2:
        a, b = dip32_rows
        if (
            a["bus"] != b["bus"]
            or a["rw_line"] != b["rw_line"]
            or a["address_mask"] != b["address_mask"]
            or a["matching_lines"] != b["matching_lines"]
        ):
            raise ValueError(
                "AT28C010 and AT28C040 were expected to share an identical "
                "bus_config (D-09 premise) but diverged"
            )


# ===========================================================================
# 5. EMITTER
# ===========================================================================


def emit_cpp_header(rows: list) -> str:
    """Emit the C++ header text from validated rows.

    Matches the in-tree validation_matrix.h convention: banner, blank line,
    #pragma once, includes, a *_COUNT define, a local row-struct typedef, then
    a static const table. Does NOT re-declare bus_config_t (that lives in
    include/firestarter.h) -- only a small wrapper row struct carrying the
    chip/pinout name and mem_size alongside the bus_config initializer.
    """
    parts = []
    parts.append(BANNER)
    parts.append("#pragma once\n")
    parts.append("\n")
    parts.append("#include <stdint.h>\n")
    parts.append('#include "firestarter.h"\n')
    parts.append("\n")
    parts.append(f"#define SDP_BUS_CONFIG_COUNT {len(rows)}\n")
    parts.append("\n")
    parts.append("typedef struct {\n")
    parts.append("    const char* chip_name;\n")
    parts.append("    const char* pinout_name;\n")
    parts.append("    uint32_t mem_size;\n")
    parts.append("    bus_config_t bus_config;\n")
    parts.append("} sdp_bus_config_row_t;\n")
    parts.append("\n")
    parts.append("static const sdp_bus_config_row_t SDP_BUS_CONFIGS[] = {\n")
    for row in rows:
        address_lines_str = ", ".join(f"0x{v:02X}" for v in row["address_lines"])
        # Pad the address_lines initializer to ADDRESS_LINES_SIZE entries so
        # the array-of-uint8_t member is fully (not partially) initialized --
        # remaining trailing slots are zero-filled by the C++ initializer
        # rules, matching the runtime's own uninitialized-tail behavior.
        parts.append("    {\n")
        parts.append(f'        "{row["chip_name"]}",\n')
        parts.append(f'        "{row["pinout_name"]}",\n')
        parts.append(f"        {row['mem_size']}UL,\n")
        parts.append("        {\n")
        parts.append(f"            {{ {address_lines_str} }},\n")
        parts.append(f"            0x{row['address_mask']:08X}UL,\n")
        parts.append(f"            {row['matching_lines']},\n")
        parts.append(f"            {row['rw_line']},\n")
        parts.append("            0xFF,\n")  # vpp_line
        parts.append("            0x00000000UL\n")  # static_high_mask
        parts.append("        }\n")
        parts.append("    },\n")
    parts.append("};\n")
    return "".join(parts)


# ===========================================================================
# 6. CLI
# ===========================================================================


def _build_argparser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="gen_sdp_bus_config.py",
        description=(
            "Derive + emit the bus_config_t ground truth for the Phase-116 "
            "SDP trace suites, from the host's own convert_to_programmer path."
        ),
    )
    p.add_argument(
        "--target",
        type=Path,
        default=_TARGET_DEFAULT,
        help=(
            "Output path for the generated header "
            "(default: firestarter/test/native/avr/_shared/sdp_bus_config.h)."
        ),
    )
    p.add_argument(
        "--pinouts",
        type=Path,
        default=_PINOUTS_DEFAULT,
        help=(
            "Path to pinouts.json to derive from (default: the real "
            "firestarter_app/firestarter/data/pinouts.json). Fails closed "
            "when the given path is missing -- never silently falls back "
            "to the real file."
        ),
    )
    p.add_argument(
        "--check",
        action="store_true",
        help=(
            "Derive, validate, render, and compare against the existing "
            "--target file. Print a diff summary and return non-zero on "
            "mismatch without writing."
        ),
    )
    return p


def main() -> int:
    """Entry point. Returns 0/1/2 for ok/validation-fail/chip-or-pinout-not-found."""
    args = _build_argparser().parse_args()

    try:
        rows = derive_rows(args.pinouts)
    except DerivationError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    try:
        validate_rows(rows)
    except ValueError as e:
        print(f"ERROR: derivation validation failed: {e}", file=sys.stderr)
        return 1

    output = emit_cpp_header(rows)

    if args.check:
        if not args.target.is_file():
            print(f"DRIFT: target does not exist: {args.target}", file=sys.stderr)
            return 1
        existing = args.target.read_text(encoding="utf-8")
        if existing != output:
            print(
                f"DRIFT: {args.target} differs from a fresh regeneration "
                f"({len(existing)} bytes committed vs {len(output)} bytes "
                f"regenerated)",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {args.target} matches a fresh regeneration")
        return 0

    args.target.parent.mkdir(parents=True, exist_ok=True)
    args.target.write_text(output, encoding="utf-8", newline="\n")
    print(f"OK: wrote {args.target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
