#!/usr/bin/env python3
"""
Firestarter v1.13 validation matrix codegen.

Reads tools/validation_matrix_spec.json (authored input, D-01) and emits a
deterministic C++ header for the native Unity test suites:

  firestarter/test/native/avr/_shared/validation_matrix.h

Mirrors the established tools/catalog/codegen.py shape:
  - Validate-first: validate_spec() raises ValueError on any schema violation
    BEFORE emission (T-71-INPUT mitigation).
  - Deterministic: sorted family/protocol order, no timestamps, LF endings.
  - Banner: DO NOT EDIT with re-run instructions.
  - Path.write_text(encoding="utf-8", newline="\\n") for byte-identical output.

Exit codes:
  0 — spec valid, header emitted successfully
  1 — spec validation failed (schema error)
  2 — spec file not found

HARN-02 / D-01 / LCAT-05 analog.
"""

import argparse
import json
import sys
from pathlib import Path

# ===========================================================================
# 1. DEFAULTS (relative to this script's location)
# ===========================================================================

_TOOLS_DIR = Path(__file__).parent
_SPEC_DEFAULT = _TOOLS_DIR / "validation_matrix_spec.json"
_TARGET_DEFAULT = (
    _TOOLS_DIR.parent.parent
    / "firestarter"
    / "test"
    / "native"
    / "avr"
    / "_shared"
    / "validation_matrix.h"
)

# ===========================================================================
# 2. SCHEMA VALIDATION (T-71-INPUT mitigation)
# ===========================================================================

BANNER = (
    "/* DO NOT EDIT -- generated by tools/gen_validation_header.py\n"
    " * Re-run after editing tools/validation_matrix_spec.json */\n"
    "\n"
)


def validate_spec(spec: dict) -> None:
    """Raise ValueError on any schema violation before emission.

    Validates:
    - Top-level schema_version is an integer.
    - Top-level families is a non-empty list.
    - Each family has required keys: id, handler, protocols.
    - protocols is a non-empty list of integers.
    """
    if not isinstance(spec.get("schema_version"), int):
        raise ValueError(
            "spec must have integer 'schema_version'; "
            f"got {spec.get('schema_version')!r}"
        )
    families = spec.get("families")
    if not isinstance(families, list) or not families:
        raise ValueError(f"spec must have non-empty 'families' list; got {families!r}")
    for fam in families:
        if not isinstance(fam, dict):
            raise ValueError(f"each family entry must be a dict; got {fam!r}")
        for key in ("id", "handler", "protocols"):
            if key not in fam:
                raise ValueError(
                    f"family {fam.get('id', fam)!r} missing required key {key!r}"
                )
        protocols = fam["protocols"]
        if not isinstance(protocols, list) or not protocols:
            raise ValueError(
                f"family {fam['id']!r}: 'protocols' must be a non-empty list; "
                f"got {protocols!r}"
            )
        for proto in protocols:
            if not isinstance(proto, int):
                raise ValueError(
                    f"family {fam['id']!r}: protocol {proto!r} must be an int "
                    f"(use decimal 7 not '0x07')"
                )


# ===========================================================================
# 3. EMITTER
# ===========================================================================


def emit_cpp_header(spec: dict) -> str:
    """Emit the C++ header text from a validated spec.

    One VAL_FAMILIES row per (protocol, family_id, handler) triple.
    Families are emitted in spec order; protocols within each family are
    sorted ascending. Total row count = VAL_FAMILY_COUNT.
    """
    families = spec["families"]

    # Build flattened row list: (protocol_int, family_id, handler)
    rows: list[tuple[int, str, str]] = []
    for fam in families:
        for proto in sorted(fam["protocols"]):
            rows.append((proto, fam["id"], fam["handler"]))

    parts: list[str] = []
    parts.append(BANNER)
    parts.append("#pragma once\n")
    parts.append("\n")
    parts.append("#include <stdint.h>\n")
    parts.append("\n")
    parts.append(f"#define VAL_FAMILY_COUNT {len(rows)}\n")
    parts.append("\n")
    parts.append("typedef struct {\n")
    parts.append("    uint32_t protocol;\n")
    parts.append("    const char* family_id;\n")
    parts.append("    const char* handler_name;\n")
    parts.append("} val_family_entry_t;\n")
    parts.append("\n")
    parts.append("static const val_family_entry_t VAL_FAMILIES[] = {\n")
    for proto, fam_id, handler in rows:
        parts.append(f'    {{ 0x{proto:02X}, "{fam_id}", "{handler}" }},\n')
    parts.append("};\n")
    return "".join(parts)


# ===========================================================================
# 4. CLI
# ===========================================================================


def _build_argparser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="gen_validation_header.py",
        description="Generate validation_matrix.h from validation_matrix_spec.json.",
    )
    p.add_argument(
        "--spec",
        type=Path,
        default=_SPEC_DEFAULT,
        help="Path to validation_matrix_spec.json (default: tools/validation_matrix_spec.json).",
    )
    p.add_argument(
        "--target",
        type=Path,
        default=_TARGET_DEFAULT,
        help=(
            "Output path for the generated header "
            "(default: firestarter/test/native/avr/_shared/validation_matrix.h)."
        ),
    )
    return p


def main() -> int:
    """Entry point.  Returns 0/1/2 for ok/schema-fail/spec-not-found."""
    args = _build_argparser().parse_args()

    if not args.spec.is_file():
        print(f"ERROR: spec not found: {args.spec}", file=sys.stderr)
        return 2

    spec = json.loads(args.spec.read_text(encoding="utf-8"))

    try:
        validate_spec(spec)
    except ValueError as e:
        print(f"ERROR: spec validation failed: {e}", file=sys.stderr)
        return 1

    output = emit_cpp_header(spec)

    args.target.parent.mkdir(parents=True, exist_ok=True)
    args.target.write_text(output, encoding="utf-8", newline="\n")
    print(f"OK: wrote {args.target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
