#!/usr/bin/env python3
"""
Firestarter v1.2 log-message catalog codegen.

Reads tools/catalog/messages.toml (or a vendored copy in a sub-repo's
tools/catalog/ directory) and emits one of three deterministic outputs:

  --language cpp        -> messages.h   (header guard, severity defines,
                                         MSG_* ID defines, PROGMEM extern,
                                         MSG_PARAM_COUNT macro)
  --language cpp-table  -> messages.c   (designated-init 256-byte
                                         PROGMEM param-byte-count table)
  --language python     -> messages.py  (severity codes, MSG_* ID constants,
                                         MessageDef dataclass, CATALOG dict)

Determinism contract (LCAT-05): two consecutive runs against the same catalog
file produce byte-identical output. Achieved by:
  - sorting messages by id ascending before emission
  - no timestamps, hostnames, or hashes in the banner
  - LF line endings via Path.write_text(..., newline='\n')
  - upper-case 2-digit hex literals ("0x%02X")
  - explicit dict iteration via sorted(...)

Validation (LCAT-02 + LCI-04): the --check flag runs the full 10-rule catalog
validator and exits 1 on any violation. Validation also runs unconditionally
before emission, so an invalid catalog never produces output.

Stdlib only (Python 3.11+ for tomllib).
"""

import argparse
import re
import sys
import tomllib
from pathlib import Path

# ===========================================================================
# 1. CONFIGURATION
# ===========================================================================

VALID_SEVERITIES = ("OK", "INIT", "MAIN", "END", "INFO", "WARN", "ERROR", "DATA")
SEVERITY_CODES = {
    "OK":    0x01,
    "INIT":  0x02,
    "MAIN":  0x03,
    "END":   0x04,
    "INFO":  0x05,
    "WARN":  0x06,
    "ERROR": 0x07,
    "DATA":  0x08,
}

VALID_PARAM_TYPES = ("u8", "u16", "u24", "u32", "i8", "i16", "i32", "ascii_str")
PARAM_TYPE_BYTES = {
    "u8":        1,
    "u16":       2,
    "u24":       3,
    "u32":       4,
    "i8":        1,
    "i16":       2,
    "i32":       4,
    # ascii_str is variable length on the wire; we store 0xFF in the param-byte
    # table to flag "variable" (callers must use a length prefix).
    "ascii_str": None,
}

VALID_RENDERS = (
    "dec", "hex", "hex_byte", "hex_word", "hex_addr", "hex_dword",
    "signed_dec", "ascii_char", "ascii_str",
)

DEFAULT_RENDER_BY_TYPE = {
    "u8":        "dec",
    "i8":        "signed_dec",
    "u16":       "dec",
    "i16":       "signed_dec",
    "u24":       "hex_addr",
    "u32":       "hex",
    "i32":       "signed_dec",
    "ascii_str": "ascii_str",
}

VALID_WIRE_FORMATS = ("id_frame", "text")
NAME_PATTERN = re.compile(r"^MSG_[A-Z][A-Z0-9_]*$")

# printf-style specifier matcher. Matches one specifier (excluding "%%").
# Specifier grammar (subset used in the catalog):
#   % [flags] [width] [length] type
# where:
#   flags   = '#' | '0'    (single optional)
#   width   = one or more digits
#   length  = 'l' | 'h'    (single optional)
#   type    = d | u | x | X | s | c
# Examples covered: %d %u %s %c %lu %lx %ld %02x %06x %#04x %02X %06lx %04x %lx
PRINTF_SPEC_RE = re.compile(r"%(?:%|[#0]?[0-9]*[lh]?[duxXsc])")

# 24-byte total wire-param budget for non-ascii_str messages (rule 10).
PARAM_BUDGET_BYTES = 24

CPP_BANNER_TEMPLATE = (
    "/*\n"
    " * Project Name: Firestarter\n"
    " * Copyright (c) 2024 Henrik Olsson\n"
    " *\n"
    " * Permission is hereby granted under MIT license.\n"
    " *\n"
    " * Firestarter -- v1.2 log-message catalog ({side})\n"
    " *\n"
    " * DO NOT EDIT -- generated by tools/catalog/codegen.py from\n"
    " *               tools/catalog/messages.toml.\n"
    " * Re-run codegen after editing the canonical catalog.\n"
    " *\n"
    " * Catalog version: {version}\n"
    " * Total messages: {count}\n"
    " */\n"
)

PY_BANNER_TEMPLATE = (
    '"""\n'
    "Project Name: Firestarter\n"
    "Copyright (c) 2024 Henrik Olsson\n"
    "\n"
    "Permission is hereby granted under MIT license.\n"
    "\n"
    "Firestarter -- v1.2 log-message catalog (host side)\n"
    "\n"
    "DO NOT EDIT -- generated by tools/catalog/codegen.py from\n"
    "              tools/catalog/messages.toml.\n"
    "Re-run codegen after editing the canonical catalog.\n"
    "\n"
    "Catalog version: {version}\n"
    "Total messages: {count}\n"
    '"""\n'
)


# ===========================================================================
# 2. CATALOG VALIDATION (LCAT-02 + LCI-04)
# ===========================================================================

class CatalogError(Exception):
    """Raised by validate_catalog() on any rule violation."""


def _count_printf_specs(format_str):
    """Count printf specifiers in format_str, excluding literal '%%'."""
    n = 0
    for m in PRINTF_SPEC_RE.finditer(format_str):
        if m.group(0) != "%%":
            n += 1
    return n


def validate_catalog(catalog):
    """Run all 10 validation rules. Raise CatalogError on first failure."""
    if not isinstance(catalog, dict):
        raise CatalogError("Top-level catalog must be a TOML table.")

    meta = catalog.get("catalog")
    if not isinstance(meta, dict) or "version" not in meta:
        raise CatalogError("Missing [catalog] table or [catalog].version key.")
    if not isinstance(meta["version"], int):
        raise CatalogError("[catalog].version must be an integer.")

    messages = catalog.get("messages")
    if not isinstance(messages, list) or not messages:
        raise CatalogError("Missing or empty [[messages]] array of tables.")

    seen_ids = {}
    seen_names = {}

    for msg in messages:
        if not isinstance(msg, dict):
            raise CatalogError("Every [[messages]] entry must be a TOML table.")

        # Rule 1: id missing / not int / out of range / duplicate
        mid = msg.get("id")
        if mid is None:
            raise CatalogError(f"Missing 'id' field in entry: {msg!r}")
        if not isinstance(mid, int) or isinstance(mid, bool):
            raise CatalogError(
                f"Field 'id' must be an integer; got {type(mid).__name__} "
                f"({mid!r}) in entry {msg.get('name', '<no name>')}"
            )
        if mid < 0 or mid > 255:
            raise CatalogError(
                f"Field 'id' out of range [0, 255]: 0x{mid:X} in entry "
                f"{msg.get('name', '<no name>')}"
            )
        if mid in seen_ids:
            other = seen_ids[mid]
            raise CatalogError(
                f"Duplicate ID 0x{mid:02X}: '{msg.get('name', '<no name>')}' "
                f"conflicts with prior '{other}'"
            )

        # Rule 2: name missing / wrong format / duplicate
        name = msg.get("name")
        if name is None or not isinstance(name, str):
            raise CatalogError(
                f"Missing or non-string 'name' for ID 0x{mid:02X}"
            )
        if not NAME_PATTERN.match(name):
            raise CatalogError(
                f"Invalid name format for ID 0x{mid:02X}: '{name}' "
                f"(must match ^MSG_[A-Z][A-Z0-9_]*$)"
            )
        if name in seen_names:
            other_id = seen_names[name]
            raise CatalogError(
                f"Duplicate name '{name}' at ID 0x{mid:02X} "
                f"(prior ID 0x{other_id:02X})"
            )

        # Rule 3: format missing or empty
        fmt = msg.get("format")
        if not isinstance(fmt, str) or fmt == "":
            raise CatalogError(
                f"Missing or empty 'format' for ID 0x{mid:02X} ({name})"
            )

        # Rule 4: params missing / not a list of tables
        params = msg.get("params")
        if not isinstance(params, list):
            raise CatalogError(
                f"Field 'params' must be a list for ID 0x{mid:02X} ({name})"
            )
        for i, p in enumerate(params):
            if not isinstance(p, dict):
                raise CatalogError(
                    f"params[{i}] must be a table in ID 0x{mid:02X} ({name})"
                )

        # Rule 5: each param's type valid
        for i, p in enumerate(params):
            ptype = p.get("type")
            if ptype not in VALID_PARAM_TYPES:
                raise CatalogError(
                    f"Invalid param type '{ptype}' at params[{i}] in "
                    f"ID 0x{mid:02X} ({name}). Allowed: "
                    f"{sorted(VALID_PARAM_TYPES)}"
                )

        # Rule 6: each param's render (if present) valid
        for i, p in enumerate(params):
            r = p.get("render")
            if r is not None and r not in VALID_RENDERS:
                raise CatalogError(
                    f"Invalid render '{r}' at params[{i}] in ID 0x{mid:02X} "
                    f"({name}). Allowed: {sorted(VALID_RENDERS)}"
                )

        # Rule 7: severity valid
        sev = msg.get("severity")
        if sev not in VALID_SEVERITIES:
            raise CatalogError(
                f"Invalid severity '{sev}' for ID 0x{mid:02X} ({name}). "
                f"Allowed: {list(VALID_SEVERITIES)}"
            )

        # Rule 8: wire_format valid; text entries must have empty params
        wf = msg.get("wire_format", "id_frame")
        if wf not in VALID_WIRE_FORMATS:
            raise CatalogError(
                f"Invalid wire_format '{wf}' for ID 0x{mid:02X} ({name}). "
                f"Allowed: {list(VALID_WIRE_FORMATS)}"
            )
        if wf == "text" and len(params) != 0:
            raise CatalogError(
                f"wire_format=text entries must have params=[] "
                f"(ID 0x{mid:02X} {name} has {len(params)} params)"
            )

        # Rule 9: format-spec count must match param count (skipped for text).
        if wf == "id_frame":
            spec_count = _count_printf_specs(fmt)
            if spec_count != len(params):
                raise CatalogError(
                    f"Format-vs-param-count mismatch for ID 0x{mid:02X} "
                    f"({name}): format has {spec_count} printf "
                    f"specifier(s), params has {len(params)}. "
                    f"format={fmt!r}"
                )

        # Rule 10: total wire-param byte budget <= 24 (non-ascii_str)
        # ascii_str is variable; the budget rule applies to fixed-width params
        # only. The 24-byte cap ensures the largest fixed-shape frame fits in
        # the AVR's 64-byte UART TX buffer (4 magic + 1 len + 1 id + 24 params
        # + 1 crc + 1 nl = 32 bytes).
        fixed_bytes = 0
        for p in params:
            w = PARAM_TYPE_BYTES.get(p["type"])
            if w is not None:
                fixed_bytes += w
        if fixed_bytes > PARAM_BUDGET_BYTES:
            raise CatalogError(
                f"Param byte budget exceeded for ID 0x{mid:02X} ({name}): "
                f"{fixed_bytes} > {PARAM_BUDGET_BYTES}"
            )

        seen_ids[mid] = name
        seen_names[name] = mid

    return True


# ===========================================================================
# 3. HELPERS
# ===========================================================================

def _param_wire_bytes(params):
    """Return integer wire-byte count for fixed-shape params, or None when any
    param is variable-length (ascii_str). The caller decides how to render
    'variable' in the output (the PROGMEM table uses 0xFF for that)."""
    total = 0
    for p in params:
        w = PARAM_TYPE_BYTES.get(p["type"])
        if w is None:
            return None  # variable-length present
        total += w
    return total


def _load_catalog(catalog_path):
    text = catalog_path.read_text(encoding="utf-8")
    return tomllib.loads(text)


def _sorted_messages(catalog):
    return sorted(catalog["messages"], key=lambda m: m["id"])


# ===========================================================================
# 4. EMITTERS
# ===========================================================================

def emit_cpp_header(catalog):
    """Render messages.h source text."""
    version = catalog["catalog"]["version"]
    messages = _sorted_messages(catalog)
    count = len(messages)

    parts = []
    parts.append(CPP_BANNER_TEMPLATE.format(
        side="C++ firmware side",
        version=version,
        count=count,
    ))
    parts.append("\n")
    parts.append("#ifndef __MESSAGES_H__\n")
    parts.append("#define __MESSAGES_H__\n")
    parts.append("\n")
    parts.append("#ifdef __cplusplus\n")
    parts.append('extern "C" {\n')
    parts.append("#endif\n")
    parts.append("\n")
    parts.append("#include <stdint.h>\n")
    parts.append("#include <avr/pgmspace.h>\n")
    parts.append("\n")
    parts.append("// --- Severity codes (mirrors host catalog) ---\n")
    for sev in VALID_SEVERITIES:
        parts.append(
            f"#define MSG_SEVERITY_{sev:<6}0x{SEVERITY_CODES[sev]:02X}\n"
        )
    parts.append("\n")
    parts.append("// --- Message IDs (sorted ascending) ---\n")
    # Width: longest name + 4 chars of slack for alignment.
    max_name_len = max(len(m["name"]) for m in messages)
    name_col = max_name_len + 2
    for m in messages:
        parts.append(
            f"#define {m['name']:<{name_col}}0x{m['id']:02X}\n"
        )
    parts.append("\n")
    parts.append("// --- Param-count lookup (PROGMEM table, 256 bytes flat) ---\n")
    parts.append("// MSG_PARAM_COUNT(id) returns the wire-byte count of the params for the\n")
    parts.append("// given ID, or 0xFF for unallocated IDs or variable-length (ascii_str)\n")
    parts.append("// payloads. Callers needing fixed-shape byte counts at compile time\n")
    parts.append("// should consult the catalog directly.\n")
    parts.append("extern const uint8_t MSG_PARAM_BYTES_TABLE[256] PROGMEM;\n")
    parts.append("\n")
    parts.append(
        "#define MSG_PARAM_COUNT(id) ((uint8_t)pgm_read_byte("
        "&MSG_PARAM_BYTES_TABLE[(id)]))\n"
    )
    parts.append("\n")
    parts.append("#ifdef __cplusplus\n")
    parts.append("}\n")
    parts.append("#endif\n")
    parts.append("\n")
    parts.append("#endif  // __MESSAGES_H__\n")
    return "".join(parts)


def emit_cpp_table(catalog):
    """Render messages.c source text (256-byte PROGMEM byte-count table)."""
    version = catalog["catalog"]["version"]
    messages = _sorted_messages(catalog)
    count = len(messages)

    # Build a 256-entry mapping {id -> (bytes_or_None, name)}.
    allocated = {}
    for m in messages:
        wb = _param_wire_bytes(m["params"])
        allocated[m["id"]] = (wb, m["name"])

    parts = []
    parts.append(CPP_BANNER_TEMPLATE.format(
        side="C firmware side (PROGMEM table)",
        version=version,
        count=count,
    ))
    parts.append("\n")
    parts.append('#include "messages.h"\n')
    parts.append("\n")
    parts.append("// 256-byte PROGMEM table: index = message ID, value = wire byte count.\n")
    parts.append("// 0xFF means \"unallocated\" or \"variable-length (ascii_str present)\".\n")
    parts.append("// Designated initializers (C99) keep this readable; gcc fills the gaps\n")
    parts.append("// with the explicit 0xFF entries below so the result is unambiguous.\n")
    parts.append("const uint8_t MSG_PARAM_BYTES_TABLE[256] PROGMEM = {\n")
    for i in range(256):
        if i in allocated:
            wb, name = allocated[i]
            if wb is None:
                parts.append(f"    [0x{i:02X}] = 0xFF,  // {name} (variable: ascii_str)\n")
            else:
                parts.append(f"    [0x{i:02X}] = {wb},  // {name}\n")
        else:
            parts.append(f"    [0x{i:02X}] = 0xFF,\n")
    parts.append("};\n")
    return "".join(parts)


def emit_python(catalog):
    """Render messages.py source text."""
    version = catalog["catalog"]["version"]
    messages = _sorted_messages(catalog)
    count = len(messages)

    parts = []
    parts.append(PY_BANNER_TEMPLATE.format(version=version, count=count))
    parts.append("\n")
    parts.append("from dataclasses import dataclass\n")
    parts.append("from typing import Tuple\n")
    parts.append("\n")
    parts.append("# --- Severity codes (mirrors firmware) ---\n")
    for sev in VALID_SEVERITIES:
        parts.append(f"SEVERITY_{sev:<6}= 0x{SEVERITY_CODES[sev]:02X}\n")
    parts.append("\n")
    parts.append("SEVERITY_LABEL = {\n")
    for sev in VALID_SEVERITIES:
        parts.append(f'    SEVERITY_{sev}: "{sev}",\n')
    parts.append("}\n")
    parts.append("\n")
    parts.append("\n")
    parts.append("@dataclass(frozen=True)\n")
    parts.append("class MessageDef:\n")
    parts.append("    id: int\n")
    parts.append("    name: str\n")
    parts.append("    severity: int\n")
    parts.append("    format: str\n")
    parts.append("    params: Tuple[Tuple[str, str], ...]\n")
    parts.append("    param_bytes: int\n")
    parts.append("    wire_format: str\n")
    parts.append("\n")
    parts.append("\n")
    parts.append("# --- ID constants (sorted ascending) ---\n")
    max_name_len = max(len(m["name"]) for m in messages)
    name_col = max_name_len + 1
    for m in messages:
        parts.append(f"{m['name']:<{name_col}}= 0x{m['id']:02X}\n")
    parts.append("\n")
    parts.append("\n")
    parts.append("# --- Catalog lookup ---\n")
    parts.append("CATALOG: dict[int, MessageDef] = {\n")
    for m in messages:
        sev = m["severity"]
        params_tuple_parts = []
        for p in m["params"]:
            ptype = p["type"]
            render = p.get("render") or DEFAULT_RENDER_BY_TYPE[ptype]
            params_tuple_parts.append(f'("{ptype}", "{render}")')
        if params_tuple_parts:
            if len(params_tuple_parts) == 1:
                params_repr = f"({params_tuple_parts[0]},)"
            else:
                params_repr = "(" + ", ".join(params_tuple_parts) + ")"
        else:
            params_repr = "()"
        wb = _param_wire_bytes(m["params"])
        if wb is None:
            # Variable-length signalled in the table as -1 on the host side
            # so callers can distinguish "0 fixed bytes" from "variable".
            param_bytes_int = -1
        else:
            param_bytes_int = wb
        # Escape backslashes and quotes in format strings for Python string
        # literal embedding. The format strings are ASCII-only printf strings;
        # no smart-quotes or non-ascii expected.
        fmt_escaped = m["format"].replace("\\", "\\\\").replace('"', '\\"')
        parts.append(
            f"    0x{m['id']:02X}: MessageDef("
            f"id=0x{m['id']:02X}, "
            f'name="{m["name"]}", '
            f"severity=SEVERITY_{sev}, "
            f'format="{fmt_escaped}", '
            f"params={params_repr}, "
            f"param_bytes={param_bytes_int}, "
            f'wire_format="{m.get("wire_format", "id_frame")}"),\n'
        )
    parts.append("}\n")
    return "".join(parts)


# ===========================================================================
# 5. CLI
# ===========================================================================

LANGUAGE_EMITTERS = {
    "cpp":       emit_cpp_header,
    "cpp-table": emit_cpp_table,
    "python":    emit_python,
}


def _build_argparser():
    p = argparse.ArgumentParser(
        prog="codegen.py",
        description="Generate firmware/host catalog artifacts from the "
                    "canonical messages.toml.",
    )
    p.add_argument("--catalog", required=True, type=Path,
                   help="Path to messages.toml (canonical or vendored copy).")
    p.add_argument("--target", type=Path, default=None,
                   help="Output path (required unless --check). "
                        "Suggested suffix: .h for cpp, .c for cpp-table, "
                        ".py for python.")
    p.add_argument("--language", choices=sorted(LANGUAGE_EMITTERS.keys()),
                   default=None,
                   help="Output language (required unless --check).")
    p.add_argument("--check", action="store_true",
                   help="Validate the catalog and exit 0/1. No files written.")
    return p


def main():
    args = _build_argparser().parse_args()

    if not args.catalog.is_file():
        print(f"ERROR: catalog file not found: {args.catalog}",
              file=sys.stderr)
        return 2

    try:
        catalog = _load_catalog(args.catalog)
    except tomllib.TOMLDecodeError as e:
        print(f"ERROR: failed to parse TOML in {args.catalog}: {e}",
              file=sys.stderr)
        return 1

    try:
        validate_catalog(catalog)
    except CatalogError as e:
        print(f"ERROR: catalog validation failed: {e}", file=sys.stderr)
        return 1

    if args.check:
        n = len(catalog["messages"])
        print(f"OK: catalog valid ({n} messages, version "
              f"{catalog['catalog']['version']}).")
        return 0

    if args.target is None or args.language is None:
        print("ERROR: --target and --language are required unless --check.",
              file=sys.stderr)
        return 2

    emitter = LANGUAGE_EMITTERS[args.language]
    output = emitter(catalog)

    args.target.parent.mkdir(parents=True, exist_ok=True)
    # newline='' + writing '\n' explicitly: LF endings guaranteed regardless
    # of platform (per Python docs for write_text + newline kwarg).
    args.target.write_text(output, encoding="utf-8", newline="\n")
    print(f"OK: wrote {args.target} ({args.language}, "
          f"{len(catalog['messages'])} messages).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
